language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-22
    - android-27
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22

licenses:
    - '.+'

script:
- "./gradlew assembleRelease"
